Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -14,10 +14,15 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
         
-      - name: Debugging secrets
+      - name: Check secrets availability
         run: |
-          echo "User length: ${#secrets.DOCKER_HUB_USER}"
-          echo "Password length: ${#secrets.DOCKER_HUB_PASSWORD}"
+          if [ -z "${{ secrets.DOCKER_HUB_USER }}" ] || [ -z "${{ secrets.DOCKER_HUB_PASSWORD }}" ]; then
+            echo "One or more required secrets are empty."
+            exit 1
+          else
+            echo "Secrets are present."
+          fi
+
 
       - name: Log in to Docker Hub
         run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
